Iter5
Raildoc1/go-metrics-service pull request #5
Opened 2024-11-30 13:53 UTC by Raildoc1

2024-12-01 13:30 UTC, Raildoc1 commented on internal/server/logic/counterLogic.go
> +
Хотел перенести объявление интерфейса сюда, но тогда не понятно, как быть с проверкой на конкретную ошибку `repositories.ErrNotFound` ниже

2024-12-03 22:35 UTC, s-shpak reviewed
Добавь, пожалуйста, запуск линтера в `Github Actions`. Здесь можно посмотреть как: https://github.com/s-shpak/praktikum-golangci-lint?tab=readme-ov-file#настройка-github-actions

2024-12-03 22:35 UTC, s-shpak commented on cmd/common/serverAddress.go
> +func (s *ServerAddress) Set(flagValue string) error {
Я бы не парсил строку с адресом сервера, а запускал ее ровно так, как она передана пользователем. Если пользователь ошибся, то отправить запрос просто не получится. Но если ты все же решишь парсить строку, то я рекомендую использовать `https://pkg.go.dev/net/url#Parse`

2024-12-03 22:35 UTC, s-shpak commented on internal/agent/metrics/collectors/runtimeMetricsCollector.go
> +		panic("already started")
Здесь нет смысла паниковать: лучше просто вернуть ошибку

2024-12-03 22:35 UTC, s-shpak commented on internal/agent/metrics/collectors/runtimeMetricsCollector.go
> +	started        bool
Пока это поле не защищено мьютексом, его использование не имеет смысла

2024-12-03 22:35 UTC, s-shpak commented on internal/agent/metrics/collectors/runtimeMetricsCollector.go
> +			time.Sleep(interval)
В стандартной библиотеке Go в пакете `time` есть структура `Tikcer` (https://pkg.go.dev/time#Ticker), которая очень хорошо подходит для решения этой задачи. Я советую тебе использовать ее или обертку над ней (https://pkg.go.dev/time#Tick) в связке с `select`-`case` для периодической отправки метрик с агента.

2024-12-03 22:35 UTC, s-shpak commented on internal/agent/metrics/senders/metricsSender.go
> +	ms.sendCounterDeltaWithErrorHandling("PollCount", 1)
Считать надо не количество оправок метрик на сервер, а количество их сборов

2024-12-03 22:35 UTC, s-shpak commented on internal/agent/metrics/senders/metricsSender.go
> +		fmt.Printf("%s: %s\n", metricName, err.Error())
Не используй пакет `fmt`, вместо него используй `log`. В дальнейшем мы перейдем либо на `slog`, либо на сторонний линтер типа `zap`.

2024-12-03 22:35 UTC, s-shpak commented on internal/server/handlers/updateMetricValueHTTPHandler.go
> +		w.WriteHeader(http.StatusInternalServerError)
Ошибки 5** нужно логировать

2024-12-03 22:35 UTC, s-shpak commented on internal/server/logic/counterLogic.go
> +
А в чем проблема этой ошибки ? Она может быть объявлена на уровне пакета `repository`: да, явной связи между этим интерфейсом и ошибкой не будет, но из контекста будет ясно, что объект имплементирующий этот интерфейс может возвращать ошибку из пакета хранилища

2024-12-03 22:36 UTC, s-shpak requested changes
Дай мне, пожалуйста, права контрибьютора в репозитории, чтобы я мог резолвить комментарии, которые поправлены.

2024-12-04 17:57 UTC, Raildoc1 commented on internal/server/logic/counterLogic.go
> +
ну вот выглядит так, что в таком случае объявление интерфейса здесь теряет свой смысл, т.е. мы как бы говорим: "мы готовы работать с любым классом, который который имеет методы Get и Set", но по факту мы ждем конкретные ошибки из конкретного пакета, т.е. мы как были жестко привязаны к пакету repositories, так и остались к нему привязаны, только теперь это ещё и неочевидно

единственная идея, которая тут у меня есть: вместо error возвращать какой-нибудь свой repositoryError и в публичных полях ошибок создавать его, тогда на уровне интерфейса будет понятно, что ожидается

ну или конкретно в этом случае ещё есть вариант просто не пользоваться проверками на ошибки, а добавить метод Has и явно проверять перед вызовом Get

2024-12-04 21:29 UTC, Raildoc1 commented on internal/server/handlers/updateMetricValueHTTPHandler.go
> +		w.WriteHeader(http.StatusInternalServerError)
done

2024-12-04 21:30 UTC, Raildoc1 commented on internal/agent/metrics/senders/metricsSender.go
> +		fmt.Printf("%s: %s\n", metricName, err.Error())
done

2024-12-04 21:30 UTC, Raildoc1 commented on internal/agent/metrics/senders/metricsSender.go
> +	ms.sendCounterDeltaWithErrorHandling("PollCount", 1)
done

2024-12-04 21:31 UTC, Raildoc1 commented on internal/agent/metrics/collectors/runtimeMetricsCollector.go
> +			time.Sleep(interval)
done

2024-12-04 21:31 UTC, Raildoc1 commented on internal/agent/metrics/collectors/runtimeMetricsCollector.go
> +	started        bool
done

2024-12-04 21:31 UTC, Raildoc1 commented on internal/agent/metrics/collectors/runtimeMetricsCollector.go
> +		panic("already started")
done

2024-12-04 21:31 UTC, Raildoc1 commented on cmd/common/serverAddress.go
> +func (s *ServerAddress) Set(flagValue string) error {
done

2024-12-06 15:40 UTC, s-shpak commented on internal/server/data/storage/memory/memStorage.go
В именах файлов в Go слова разделяются либо нижним подчеркиванием, либо тире.

2024-12-06 15:40 UTC, s-shpak commented on internal/agent/metrics/sender/metricsSender.go
> +		ms.storage.FlushPollsCount()
Я бы вынес этот вызов в файл `agent.go`: кажется, что сбрасывать счетчик -- не задача отправителя

2024-12-06 15:40 UTC, s-shpak commented on internal/server/logic/counterLogic.go
> +
Это хорошое замечание.

Здесь действительно возникает неявная связь. В логике Go обертывание ошибок имеет такой смысл: я вызываю объект какого-то интерфейса, он возвращает ошибку. Это может быть не напрямую ошибка из пакета `repository` -- может быть объект, имплементирующий интерфейс `Repository`, обертка над настоящим репозиторием, но, если в цепи ошибок есть интересующая нас, которая указывает на то, что запись на каком-то этапе не была найдена в хранилище, то мы сможем ее обработать определенным образом.

Возвращать конкретный тип ошибки, отличный от интерфейса `error`, не принято из-за подхода с оборачиванием ошибок.

Я согласен, что это неиделаьная ситуация, но это принятая практика в языке

WDYT ?

2024-12-06 15:41 UTC, s-shpak requested changes
См. оставшиеся комментарии

2024-12-06 16:41 UTC, Raildoc1 commented on internal/server/data/storage/memory/memStorage.go
done

2024-12-06 16:41 UTC, Raildoc1 commented on internal/agent/metrics/sender/metricsSender.go
> +		ms.storage.FlushPollsCount()
done

2024-12-06 16:52 UTC, Raildoc1 commented on internal/server/logic/counterLogic.go
> +
Здесь остановился на варианте с методом Has, поэтому теперь проверки на ошибку нет

А вообще вынес объявление ошибок из repositories в data/errors.go, чтобы показать, что это ошибки всего слоя данных, а не конкретного пакета, по идее если учитывать, что здесь используется конкретная архитектура: CSR, то, наверное, вполне логично будет от любой реализации repository ожидать ошибки со слоя Data

Ещё нашёл такой вариант:
https://medium.com/@shershnev/layered-architecture-implementation-in-golang-6318a72c1e10
Здесь интерфейсы объявляются в отдельном файле в рамках слоя, в принципе, выглядит тоже неплохо

Но лично мне понравилось объявление интерфейсов рядом с местом использования, поэтому оставил, как было

2024-12-06 19:45 UTC, s-shpak commented on internal/server/logic/counterLogic.go
> +
В статье на медиуме не очень идиоматичный подход, больше похоже на код на Java с синтаксисом Go. Но иногда проекты так, конечно, пишут

Этот комментарий можно зарезолвить

2024-12-06 19:46 UTC, s-shpak approved these changes

2024-12-08 07:22 UTC, merged