Iter9
Raildoc1/go-metrics-service pull request #9
Opened 2024-12-17 17:17 UTC by Raildoc1

2024-12-20 19:52 UTC, s-shpak requested changes

2024-12-20 19:52 UTC, s-shpak commented on cmd/agent/main.go
> +			log.Fatal(err)
Кажется, что здесь не надо фаталиться: сервис и так завершает работу, достаточно просто залогировать сообщение. Кроме того из-за такого подхода может не получиться сделать graceful shutdown в дальнейшем

2024-12-20 19:52 UTC, s-shpak commented on cmd/server/config/config.go
> +	FileStoragePathFlag = "f"
Эти константы не надо экспортировать

2024-12-20 19:52 UTC, s-shpak commented on cmd/server/config/config.go
> +	DefaultFileStoragePath       = "./data.gz"
Как и эти

2024-12-20 19:52 UTC, s-shpak commented on internal/agent/metrics/sender/metrics-sender.go
> +		log.Printf("Errorln sending gauge '%s': %v", key, err)
Не очень понял идею

```suggestion
		log.Printf("Error sending gauge '%s': %v", key, err)
```

2024-12-20 19:52 UTC, s-shpak commented on internal/agent/requester/requester.go
> +	gzipwriter, err := gzip.NewWriterLevel(&body, gzip.BestSpeed)
Можно ли как-то обобщить эту логику, так чтобы ей могли пользоваться и агент, и сервер ?

2024-12-20 19:52 UTC, s-shpak commented on internal/server/data/storage/mem-storage.go
> +func (m *MemStorage) SaveToFile(filePath string) error {
В этом спринте мы добавляем обособленную часть функционала к хранилищу: запись в файл. То есть новый тип хранилища полностью повторяет функционал MemoryStore и расширяет его. Но мы оставляем возможность запустить сервис без записи в файл. Потому кажется логичным не изменять существующую структуру, и не дуплицировать функционал, а написать обертку над MemoryStore.

Для этого можно использовать композицию и встроить MemoryStore в новую структуру FileStore. При вызове сохранения, например, новая структура будет вызывать вначале добавление новой записи в память (через встроенный объект), а потом сохранение в файл.

В этом случае убедись, что ты выполняешь инициализацию нужного типа при старте сервиса (можно использовать паттерн Factory, как разбирали на первом вебинаре).

2024-12-20 19:52 UTC, s-shpak commented on internal/server/logic/interfaces.go
> +type CounterRepository interface {
Не очень ясно, зачем выносить интерфейсы в специальный файл. Почему бы не положить их рядом с кодом, где они используются ?

2024-12-20 19:52 UTC, s-shpak commented on internal/server/middleware/with-request-decompression.go
> +			logger.Errorln("failed to decompress ", err)
Именно поэтому мне не очень нравится идея передавать логгер в качестве интерфейса, а не конкретной структуры.

В zap оперделено очень много полезных функций, которые, кажется, копировать в интерфейс -- контрпродуктивно. Например, при записи сообщения лучше передать ошибку в качестве типа `Field`, что позволит писать полуструктурированные логи (json-объекты), а не просто текстовые сообщения. Я советую использовать логгер напрямую и немного почитать документацию, чтобы лучше узнать о его возможностях

2024-12-20 20:22 UTC, Raildoc1 commented on internal/agent/metrics/sender/metrics-sender.go
> +		log.Printf("Errorln sending gauge '%s': %v", key, err)
Это, видимо, при переименовании goland решил и внутри комментов поменять названия)

2024-12-20 20:28 UTC, Raildoc1 commented on internal/server/logic/interfaces.go
> +type CounterRepository interface {
в случае, например, с хэндлерами Counter- и GaugeRepository нужны более чем одному хэндлеру, а лежат они при этом в одном пакете, поэтому не получится каждому свой создать, ну или тогда надо под каждый хэндлер создавать по отдельному пакету, что усложнило бы иерархию

конкретно на слое логики они не переиспользуются, но тогда получится неоднообразно, если тут так будет, а в хэндлерах по-другому

2024-12-21 07:42 UTC, Raildoc1 commented on internal/agent/requester/requester.go
> +	gzipwriter, err := gzip.NewWriterLevel(&body, gzip.BestSpeed)
выглядит так, что не особо, переиспользуется только само оборачивание io.Writer, а это и так один вызов функции

2024-12-22 19:44 UTC, Raildoc1 commented on internal/agent/requester/requester.go
> +	gzipwriter, err := gzip.NewWriterLevel(&body, gzip.BestSpeed)
done

2024-12-22 19:44 UTC, Raildoc1 commented on internal/agent/metrics/sender/metrics-sender.go
> +		log.Printf("Errorln sending gauge '%s': %v", key, err)
done

2024-12-22 19:44 UTC, Raildoc1 commented on cmd/server/config/config.go
> +	DefaultFileStoragePath       = "./data.gz"
done

2024-12-22 19:44 UTC, Raildoc1 commented on cmd/server/config/config.go
> +	FileStoragePathFlag = "f"
done

2024-12-22 19:45 UTC, Raildoc1 commented on cmd/agent/main.go
> +			log.Fatal(err)
done

2024-12-22 19:45 UTC, Raildoc1 commented on internal/server/middleware/with-request-decompression.go
> +			logger.Errorln("failed to decompress ", err)
done

2024-12-22 19:59 UTC, Raildoc1 commented on internal/server/data/storage/mem-storage.go
> +func (m *MemStorage) SaveToFile(filePath string) error {
Не могу согласиться, что это новый тип хранилища, если бы задание подразумевало использования файла, как хранилища, т.е. писать в файл при каждом изменении и читать из файла при каждом обращении, то да

Но в задании требуется просто добавить возможность раз в N секунд делать бэкап хранилища (и уметь его восстанавливать), а само хранилище работает точно так же, как и раньше, храня всё в оперативной памяти

является ли сама запись в файл ответственность хранилища -- вопрос довольно философский, её я все таки решил вынести, но то, как сериализуется состояние MemStorage, и как оно потом восстанавливается это точно внутрення логика MemStorage, снаружи не должно быть известно, каким именно образом он сохраняет данные при Set, и каким образом он из загружает при Get

2024-12-24 15:44 UTC, s-shpak commented on internal/server/logic/interfaces.go
> +type CounterRepository interface {
Ну тогда логично создать интерфейс для каждого хендлера -- если ты разнес хендлеры на разные пакеты, то почему между ними возникает такая тесная связь в виде разделенного интерфейса ?

2024-12-24 15:46 UTC, s-shpak commented on internal/server/data/storage/mem-storage.go
> +func (m *MemStorage) SaveToFile(filePath string) error {
Я не очень понимаю, почему это философский вопрос ? Это внутрення деталь реализации хранилища, неясно, почему бизнес-логика должна об этом знать.

Мне такой дизайн не нравится, но, если хочешь, то оставь его. Но я рекомендую не менять публичный интерфейс хранилища

2024-12-24 15:49 UTC, s-shpak requested changes

2024-12-24 15:49 UTC, s-shpak commented on cmd/agent/main.go
> +	logFile, err := os.Create("./agent.log")
Кстати, а зачем писать логи в файл ? С запуском сервисов в контейнерах стало намного более принятым писать логи в stdout, чтобы приложение вообще не знало, как логи длальше аггрегируются. Если ты хочешь добавить возможность записи в файл, то я бы оставил это опцией, которая по умолчанию отключена

2024-12-24 16:23 UTC, Raildoc1 commented on internal/server/logic/interfaces.go
> +type CounterRepository interface {
так наоборот хэндлеры у меня все в одном пакете и они пользуются одними и теми же интерфейсами, которые лежат в отдельном файле interface.go
я не могу поместить интерфейсы рядом с конкретными хэндлерами, потому что некоторые интерфейсы используются более чем в одном хэндлере

2024-12-24 16:36 UTC, Raildoc1 commented on internal/server/data/storage/mem-storage.go
> +func (m *MemStorage) SaveToFile(filePath string) error {
философский в том плане, что зависит от постановки задачи:  если мы говорим, что файл для нас -- это и есть хранилище, по аналогии с бд, в которое мы пишем при любом Set, то это новый тип хранилища, у которого работа с файлом -- это деталь реализации

а если задача стоит, как: есть хранилище, которое всё хранит в оперативной памяти и мы просто хотим уметь делать бэкапы, то тогда здесь ответственностью хранилища является только умение сериализовать своё состояние, а то, куда мы делаем бэкапы, в локально созданный файл, или куда-то отправляем, то это уже детали реализации некой отдельной сущности, которая отвечает за бэкапы (какой-нибудь отдельный MemStorageBackpper)

`Доработайте код сервера, чтобы он мог с заданной периодичностью сохранять текущие значения метрик на диск в указанный файл`

Если я правильно понимаю формулировку задания: сбор метрик != сохранение метрик, т.е. мы можем раз в секунду делать Poll и только раз в несколько минут сохранять в файл, т.е. по заданию требуется именно второй вариант, а не первый

2024-12-25 15:43 UTC, Raildoc1 commented on cmd/agent/main.go
> +	logFile, err := os.Create("./agent.log")
убрал
в одном из уроков говорилось, что лучше писать в файл, поэтому и добавил

2024-12-27 15:32 UTC, s-shpak approved these changes

2024-12-27 16:22 UTC, merged